---
set_url : 
signup_page : 
ios_capabilities: {
  appiumVersion: "1.4.0",
  platformName: "iOS",
  platformVersion: "9.0",
  deviceName: "iPhone Simulator",
  browserName: "Safari",
  name: "Basic iOS Web Test",
}
